CarInsuranceMVC/nuked versions/Insurance/Insurance/Controllers/HomeController.cs
using Insurance.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Insurance.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public double getQuote(Insuree insuree)
        {
            int baseRate = 50;

            //calculate ageRate
            DateTime dob = insuree.DateOfBirth;
            int ageRate = 0;
            if (DateTime.Now.Year - dob.Year < 18)
            {
                ageRate = 100;
            }
            if (DateTime.Now.Year - dob.Year < 25 || DateTime.Now.Year - dob.Year > 100)
            {
                ageRate = 25;
            }

            //calculate carModel variables
            int carYearRate = 0;
            if (insuree.CarYear < 2000 || insuree.CarYear > 2015)
            {
                carYearRate = 25;
            }
            int carMakeRate = 0;
            if (insuree.CarMake == "Porsche")
            {
                carMakeRate = 25;
            }
            if (insuree.CarMake == "Porsche" && insuree.CarModel == "911 Carrera")
            {
                carMakeRate = 50;
            }

            //speeding ticket variables
            int speedingTicketRate = insuree.SpeedingTickets * 10;

            //Base Quote
            double quote = baseRate + ageRate + carYearRate + carMakeRate + speedingTicketRate;

            //DUI
            if (insuree.DUI)
            {
                quote = quote * 1.25;
            }

            //Coverage Level
            if (insuree.CoverageLevel)
            {
                quote = quote * 1.5;
            }

            return quote;
        }
    }
}

CarInsuranceMVC/nuked versions/Insurance/Insurance/Controllers/InsureeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Insurance.Models;

namespace Insurance.Controllers
{
    public class InsureeController : Controller
    {
        private InsuranceEntities db = new InsuranceEntities();

        // GET: Insuree
        public ActionResult Index()
        {
            return View(db.Insurees.ToList());
        }

        // GET: Insuree/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // GET: Insuree/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Insuree/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageLevel,Quote")] Insuree insuree)
        {
            
            db.Insurees.Add(insuree);
            db.SaveChanges();
            

            return View(insuree);
        }

        // GET: Insuree/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageLevel,Quote")] Insuree insuree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(insuree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(insuree);
        }

        // GET: Insuree/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Insuree insuree = db.Insurees.Find(id);
            db.Insurees.Remove(insuree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

CarInsuranceMVC/nuked versions/Insurance/Insurance/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CarInsuranceMVC/nuked versions/Insurance/Insurance/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarInsuranceMVC/nuked versions/Insurance/Insurance/Views/Home/Index.cshtml
<div class="row no-gutters m-3">
    <div class="card col mx-auto shadow">
        @using (Html.BeginForm("Create", "Insuree", FormMethod.Post))
        {
        <div class="card-body">
            <div class="row no-gutters">
                <div class="form-group col">
                    <input type="text" name="FirstName" value="" class="form-control h-100 " placeholder="First Name" />
                </div>
                <div class="form-group col">
                    <input type="text" name="LastName" value="" class="form-control h-100 " placeholder="Last Name" />
                </div>
                <div class="form-group col">
                    <input type="email" name="EmailAddress" value="" class="form-control h-100 " placeholder="Email Address" />
                </div>
                <div class="form-group col">
                    <input type="date" name="DateofBirth" value="" class="form-control h-100 " placeholder="Date of Birth" />
                </div>
            </div>
            <div class="row no-gutters">
                <div class="form-group col">
                    <input type="text" name="CarYear" value="" class="form-control" placeholder="Car Year" />
                </div>
                <div class="form-group col">
                    <input type="text" name="Car Make" value="" class="form-control" placeholder="Car Make" />
                </div>
                <div class="form-group col">
                    <input type="text" name="Car Model" value="" class="form-control" placeholder="Car Model" />
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col border p-2">
                    <div class="row mx-auto"> Have you ever had a DUI? </div>
                    <div class="row mx-auto">
                        <input type="checkbox" name="yesDUI" value="" class="m-2 border" />
                        <p>Yes</p>
                    </div>
                    <div class="row mx-auto">
                        <input type="checkbox" name="noDUI" value="" class="m-2 border" />
                        <p>No</p>
                    </div>
                </div>
                <div class="col border p-2">
                    <div class="row mx-auto"> How many speeding tickets have you had? </div>
                    <div class="row mx-auto">
                        <input type="number" name="speedingTickets" value="" class="m-2 border" />
                    </div>
                </div>
                <div class="col border p-2">
                    <div class="row mx-auto"> Would you like full coverage or liability only? </div>
                    <div class="row mx-auto">
                        <input type="radio" name="fullCoverage" value="" class="m-2 border" />
                        Full Coverage
                    </div>
                    <div class="row mx-auto">
                        <input type="radio" name="liability" value="" class="m-2 border" />
                        Liability
                    </div>
                </div>
            </div>
            <div class="row no-gutters col-12 mt-5">
                <input type="submit" name="submit" value="Submit" class="btn btn-block btn-outline-primary mx-auto" />
            </div>
        </div>
        }
        <div class="card-header text-center">
            <h5 class="m-0">Car Insurance Quote Form</h5>
        </div>
        
    </div>
</div> 